.valid_grids <- c("us_state_grid1", "us_state_grid2", "eu_grid1", "aus_grid1",
  "sa_prov_grid1", "london_boroughs_grid", "nhs_scot_grid", "india_grid1",
  "india_grid2", "argentina_grid1", "br_states_grid1", "sea_grid1",
  "mys_grid1", "fr_regions_grid1", "de_states_grid1", "us_or_counties_grid1",
  "us_wa_counties_grid1", "us_in_counties_grid1",
  "us_in_central_counties_grid1", "se_counties_grid1",
  "sf_bay_area_counties_grid1", "ua_region_grid1", "mx_state_grid1",
  "mx_state_grid2", "scotland_local_authority_grid1", "us_state_grid3",
  "italy_grid1", "italy_grid2", "be_province_grid1", "us_state_grid4",
  "jp_prefs_grid1", "ng_state_grid1", "bd_upazila_grid1", "spain_prov_grid1",
  "ch_cantons_grid1", "ch_cantons_grid2", "china_prov_grid1",
  "world_86countries_grid", "se_counties_grid2", "uk_regions1",
  "us_state_contiguous_grid1", "sk_province_grid1",
  "ch_aargau_districts_grid1", "jo_gov_grid1", "spain_ccaa_grid1",
  "spain_prov_grid2", "world_countries_grid1", "br_states_grid2",
  "china_city_grid1", "kr_seoul_district_grid1", "nz_regions_grid1",
  "sl_regions_grid1", "us_census_div_grid1", "ar_tucuman_province_grid1",
  "us_nh_counties_grid1", "china_prov_grid2", "pl_voivodeships_grid1",
  "us_ia_counties_grid1", "us_id_counties_grid1", "ar_cordoba_dep_grid1",
  "us_fl_counties_grid1", "ar_buenosaires_communes_grid1", "nz_regions_grid2",
  "oecd_grid1")
